### ISSUE TITLE
Site layout is not mobile friendly

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Dash-Industry-Forum.github.io#22]
Google identifies 3 issues in the layout. This is bad for mobile readability as well as search rankings for all that we publiush. 

![image](https://user-images.githubusercontent.com/2762250/50388462-f2043300-06cb-11e9-99ad-9adf503e568b.png)

![image](https://user-images.githubusercontent.com/2762250/50388456-d7ca5500-06cb-11e9-8fb4-74aa582aa96e.png)

**Comment by acbegen** [comment]
This is completed in my fork.

**Comment by acbegen** [comment]
New site passes google's mobile friendliness test.

**Comment by wilaw** [comment]
Great. Thanks for those improvements. Has your fork been merged?

**Comment by edrthomas** [comment]
yes, in commit ad809938f888e7a225ecbc90884463a99031aed3
