### ISSUE TITLE
Update the Academic Events

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Dash-Industry-Forum.github.io#50]
The Academic Event page is not up-to-date https://dashif.org/academic/

It also has many pointers to the internal github, but should point to the dashif web page.

Please update.

**Comment by timse7** [comment]
It points to the wiki which is publicly available to everybody afaik (just tested for one link and it works). I agree it needs to be updated and I believe @acbegen wanted to do that.

**Comment by acbegen** [comment]
Yes, I should take care of that. I wonder whether we just point to the wiki from that menu link and don't bother updating the page itself (it is a duplicate with the wiki IMO). Comments?

**Comment by timse7** [comment]
Hmm, I did not see your message @acbegen and I updated text now but I wonder whether I should "Commit directly to the hugo branch." or "Create a new branch for this commit and start a pull request."? Please advice, thanks!

**Comment by timse7** [comment]
Done.
