### ISSUE TITLE
Create sub-menu for the Identifiers tab

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Dash-Industry-Forum.github.io#8]
Current DASH IF website has a sub-menu for the identifiers tab

![image](https://user-images.githubusercontent.com/2762250/45128964-b0a84180-b135-11e8-8bf5-949d3b939a35.png)

**Comment by edrthomas** [comment]
Added in commit
6c564136ef3232b9c52a27618f57ea16291bf5ab
